### PR TITLE
releng - Ignore integration tests for forked pull requests

### PR DESCRIPTION
**Pull request by herzog31**
see https://github.com/adobe/commerce-cif-magento/pull/16

### CODE REVIEW

**Comment by hasnarobert** [comment]
Is this meant as a permanent change?

**Comment by herzog31** [comment]
@hasnarobert Until we find a better solution. Feel free to make suggestions.

**Comment by hasnarobert** [comment]
A better solution for what? Why are we disabling ITs for PRs from forks?

**Comment by herzog31** [comment]
@hasnarobert to run ITs, we need to deploy the actions. For deploying actions you need credentials. Forked PRs might potentially contain malicious code that could steal those credentials. So we configured CircleCI to not provide the credentials for forked PRs. The ITs can be executed by either creating a branch of the PR in our repo or executing them manually after a review.

**Comment by hasnarobert** [comment]
Ok, got it. I understand why this is a problem but I still don't like that PRs created by us are handled differently than PRs created by external contributors. This solution should work for the time being but I would like us to revise this approach once we start receiving PRs from external contributors.
Maybe create namespaces and credentials on the fly for when ITs are run and delete them after.

**Pull request merged**
